name: 'Advanced Installer Tool'
description: 'Deploys Advanced Installer tool and builds an AIP project.'
author: 'Caphyon'
inputs:
  advinst-version:
    description: 'Advanced Installer version to deploy. This parameter is optional. If not specified the latest version will be used. For a list of valid versions please see http://www.advancedinstaller.com/version-history.html'
    required: false
  advinst-license:
    description: 'Advanced Installer license ID. This parameter is optional if you are using a simple project type.'
    required: false
  advinst-enable-automation:
    description: 'Enable Advanced Installer PowerShell automation. This capability needs Advanced Installer 16.1 or higher.'
    required: false
    default: 'false'
  aip-path:
    description: 'The Advanced Installer project (.AIP) to be built.'
    required: false
  aip-build-name:
    description: 'Advanced Installer project build to use'
    required: false
  aip-package-name:
    description: 'Output package name'
    required: false
  aip-output-dir:
    description: 'Result package location'
    required: false
  aip-commands:
    description: 'Additional arguments passed along with the package build command'
    required: false

runs:
  using: 'node16'
  pre:  'dist/pre/index.js'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'

branding:
  icon: 'box'
  color: 'blue'
